### ISSUE TITLE
get bad result

### ISSUE THREAD

**Issue by dnqf11** [ShirleyMaxx/VMarker-Pro#1]
https://github.com/ShirleyMaxx/VMarker-Pro/assets/113501640/cc50b8a2-7494-4c13-a62b-0e4916e206b6

thanks for your great work， maybe the virtual markers estimation is not precision so that final pose estimation is bad

**Comment by ShirleyMaxx** [comment]
Thanks for your interest. Our results exhibit jitter mainly because we didn't use any temporal information. The results are inferred frame by frame. Applying some post-processing smoothing should yield better results.
